# Generated by Django 3.2 on 2021-04-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_picture',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
